// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "ffi_rust";





        [DllImport(__DllName, EntryPoint = "configure_probe", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void configure_probe(byte* url_chars, int interval, int id, delegate* unmanaged[Cdecl]<int, bool, void> on_probe_result);

        [DllImport(__DllName, EntryPoint = "stop_probe", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void stop_probe(byte* url_chars);


    }



}
